openapi: 3.0.0
info:
  version: 1.0.0
  title: Ares Web Services
  license:
    name: MIT
servers:
  - url: http://api.badape.online/v1

paths:
  /store/{account}/team:
    get:
      summary: Get Player Roster
      operationId: getTeam
      security:
        - platform_key: []
      parameters:
        - in: path
          name: account
          required: true
          description: The player id of the player to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Roster"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /store/{account}/roster:
    get:
      summary: Get Player Roster
      operationId: getAccountRoster
      security:
        - platform_key: []
      parameters:
        - in: path
          name: account
          required: true
          description: The player id of the player to retrieve
          schema:
            type: string

      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Roster"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Buy hero
      operationId: buyAccountRoster
      security:
        - platform_key: []
      parameters:
        - in: path
          name: account
          required: true
          description: The player id of the player to retrieve
          schema:
            type: string

      tags:
        - Item
      requestBody:
        $ref: "#/components/schemas/Hero"
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /store/refresh:
    post:
      summary: Refresh store items
      operationId: refreshStore
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /content/news:
    get:
      summary: Get Game News
      operationId: getGameNews
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/News"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    News:
      type: object
      properties:
        title:
          type: string
        body:
          type: string
    Hero:
      type: object
      properties:
        game_id:
          type: integer
          format: int64
        roster:
          type: boolean
    Heroes:
      type: object
      properties:
        heroes:
          type: array
          items:
            $ref: "#/components/schemas/Hero"
    Roster:
      type: array
      items:
        $ref: "#/components/schemas/Hero"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

  securitySchemes:
    platform_key:
      type: apiKey
      name: X-PLATFORM-KEY
      in: header


