openapi: 3.0.0
info:
  version: 1.0.0
  title: Ares Web Services
  license:
    name: MIT
servers:
  - url: http://api.badape.online/v1

paths:
  /player/dev/{playerId}:
    get:
      summary: Info for a specific player
      operationId: getPlayerByDevPlayerId
      security:
        - api_key: []
      tags:
        - players
      parameters:
        - name: playerId
          in: path
          required: true
          description: The player id 64bit of the player to retrieve
          schema:
            type: string
            maximum: 20
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Players"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /player/dev/{playerId}/roster:
    get:
      summary: Get Player Roster
      operationId: getPlayerRoster
      security:
        - api_key: []
      parameters:
        - name: playerId
          in: path
          required: true
          description: The player id of the player to retrieve
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Roster"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /hero/data:
    get:
      summary: get Heroes data
      operationId: heroesConfig
      tags:
        - Item
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Heroes"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /hero/data/{heroId}:
    get:
      summary: get Hero data
      operationId: heroData
      tags:
        - Item
      parameters:
        - name: heroId
          in: path
          required: true
          description: The hero id
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Hero"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /hero/buy:
    post:
      summary: Buy item
      operationId: buyHero
      tags:
        - Item
      requestBody:
        $ref: "#/components/schemas/BuyItem"
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Player:
      type: object
      required:
        - playerId
      properties:
        playerId:
          type: integer
          format: int64
        credits:
          type: integer
          format: int64
    Players:
      type: array
      items:
        $ref: "#/components/schemas/Players"
    Hero:
      type: object
      properties:
        game_id:
          type: integer
          format: int64
        roster:
          type: boolean
    Heroes:
      type: object
      properties:
        heroes:
          type: array
          items:
            $ref: "#/components/schemas/Hero"
    Roster:
      type: array
      items:
        $ref: "#/components/schemas/Hero"
    Item:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int32
    Item:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int32
        credits:
          type: integer
          format: int32
    BuyItem:
      type: object
      required:
        - playerId
        - gameId
      properties:
        playerId:
          type: integer
          format: int64
        gameId:
          type: integer
          format: int32
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
      openIdConnectUrl: "http://www.example.com"
